# Generated by Django 4.2.7 on 2023-12-05 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrega', models.DateField(blank=True, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('pregunta_1', models.CharField(blank=True, max_length=100, null=True)),
                ('respuesta_1', models.IntegerField(blank=True, null=True)),
                ('pregunta_2', models.CharField(blank=True, max_length=100, null=True)),
                ('respuesta_2', models.IntegerField(blank=True, null=True)),
                ('pregunta_3', models.CharField(blank=True, max_length=100, null=True)),
                ('respuesta_3', models.IntegerField(blank=True, null=True)),
                ('pregunta_4', models.CharField(blank=True, max_length=100, null=True)),
                ('respuesta_4', models.IntegerField(blank=True, null=True)),
                ('pregunta_5', models.CharField(blank=True, max_length=100, null=True)),
                ('respuesta_5', models.IntegerField(blank=True, null=True)),
                ('flow', models.IntegerField(auto_created=0)),
                ('en_encuesta', models.BooleanField()),
                ('completa', models.BooleanField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.cliente')),
            ],
        ),
    ]
