# Generated by Django 4.2.7 on 2023-11-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MensajesRecibidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_wa', models.CharField(max_length=100, unique=True)),
                ('mensaje', models.TextField()),
                ('timestamp', models.IntegerField()),
                ('telefono_cliente', models.CharField(max_length=100)),
                ('telefono_receptor', models.CharField(max_length=100)),
            ],
        ),
    ]
