version: '3'

services:
  botdjango:
    container_name: botdjango
    image: botdjango:v0.1
    volumes:
      - ../db.sqlite3:/app/db.sqlite3
    ports:
      - "8002:8000"
    extra_hosts:
      - "mail.backoffice.com.ar:10.0.4.50"

